42organization/42gg_softwave_client

components/Layout/MenuBar.tsx, components/modal/ModalProvider.tsx, components/modal/menu/MatchTriggerModal.tsx, styles/modal/MatchTriggerModal.module.scss, types/modalTypes.ts
- softwave에서 게스트는 로그아웃 못하도록 로그아웃 버튼 제거
- softwave에서 admin이 직접 매치를 시작하게 할 수 있는 기능 추가
- 로그아웃 버튼 주석 처리
- admin이 좌측 메뉴에서 매치 슬롯 id 입력받아 매치 시작 요청 보내는 모달 추가
=> [Feat] 로그아웃 기능 삭제 및 어드민 슬롯아이디로 게임시작 요청 모달 #2

components/Layout/CurrentMatch.tsx, components/match/MatchBoard.tsx, components/match/MatchSlot.tsx, components/match/MatchSlotList.tsx, components/modal/match/CancelModal.tsx, components/modal/match/MatchEnrollModal.tsx, components/mode/modeItems/ModeCheckBox.tsx, components/mode/modeWraps/MatchModeWrap.tsx, pages/match.tsx, styles/match/MatchSlotList.module.scss, styles/mode/ModeCheckBox.module.scss, styles/mode/ModeToggle.module.scss, types/mainType.ts, types/matchTypes.ts, types/modalTypes.ts
- 일반전 대신 챌린지로, 시간 대신 슬롯 아이디로 토글 및 슬롯 수정
- enroll, cancel 시간 사용 로직 일부 삭제
- 토글을 체크박스로 변경하고 일반 대신 챌린지로 설정
- 슬롯을 시간 대신 id 표시하도록 변경
- 슬롯 신청할때 모달이 id 표시하도록 변경
- 시간 사용하는 로직 삭제
- 캔슬모달 5분 전 취소 불가능 기능 삭제
=> [Feat] 매치슬롯페이지수정 토글 슬롯 #3

components/Layout/CurrentMatch.tsx, components/Layout/NotiItem.tsx
- NotiBar.tsx -> 알림을 slotId로 띄우게 수정.
- CurrentMatch.tsx -> 상단 알림을 slotId로 띄우게 수정.
- NotiItem function 의 content 수정 및 시간 관련 함수 삭제
- makeMessage function 의 parameter 수정
=> [Feat] notiBar, currentMatchInfo slotTime을 slotId로 수정 #5

components/match/MatchBoard.tsx, components/match/MatchSlot.tsx, components/modal/ModalProvider.tsx, components/modal/match/MatchChallengeCard.tsx, components/modal/match/MatchChallengeModal.tsx, components/modal/match/MatchEnrollModal.tsx, styles/match/MatchSlot.module.scss, styles/modal/MatchChallengeCard.module.scss, styles/modal/MatchChallengeModal.module.scss, styles/modal/MatchEnrollModal.module.scss, types/modalTypes.ts
- 42gg와 치기 체크박스 체크인 경우 42gg 팀원 상대 선택하는 모달 생성
- 모드가 challange일때 띄우는 모달 생성
- 42gg 상대 3명을 get요청으로 받아와 출력하는 부분
- 슬롯을 누를 때 mode : challange로 슬롯 바로 등록요청
- 취소하거나 선택하지 않고 모달을 나가면 슬롯 delete 요청
- 상대를 선택하고 확인을 누르면 선택한 상대로 post 요청
- 새로고침 누르면 새로 3명 다시 get 요청
=> [Feat] 42gg와 치기 상대 선택 모달 #4

pages/login.tsx
- 로그인 버튼에 연결된 URL 수정
-  로그인 버튼에 연결된 URL 수정
=> [Feat] 로그인 페이지 #1

components/game/GameResultList.tsx, components/modal/afterGame/Guide.tsx, components/modal/match/MatchChallengeModal.tsx, components/modal/statChange/StatChangeModal.tsx, components/rank/RankListItem.tsx, pages/_app.tsx, pages/rank.tsx, pages/users/detail.tsx, styles/globals.css, styles/modal/AfterGameModal.module.scss, types/rankTypes.ts, utils/infinityScroll.ts, utils/recoil/myRank.ts
- 여러 에러 수정
- challenge 타입 추가되서 생기는 타입 에러 수정
- eslint error 수정
- css 에러 수정
- enroll 타입 에러 수정
- challenge 모드로 경기 종료되는 문제 rank로만 요청 보내도록 수정
=> [Fix] 여러 에러 수정 #16

components/modal/afterGame/Guide.tsx, components/modal/afterGame/RankGame.tsx, components/modal/match/MatchManualModal.tsx
- 승리 조건 수정
- 경기 종료 후 점수 입력 부분 3 -> 5 으로 상향
- 기존 3판 2선승제 -> 단판 5점 내기로 수정
=> [Feat] 기존 3판 2선 승제 에서 단판 5점 내기로 수정 및 메뉴얼 수정 #18

components/main/SearchBar.tsx, components/mode/modeItems/UserGameSearchBar.tsx
- 메인 페이지 및 전적 페이지 검색창 한글 입력 받기
- 정규표현식 (숫자 + 영어) 에서 (한글 + 영어) 로 수정  <- 숫자가 들어가는 경우가 없음
=> [수정] id검색 시 한글입력 가능하게 허용 #23

components/Layout/NotiItem.tsx
- 매칭 취소 알림 내용 수정 
- 알림벨 클릭 시 매칭 취소 알림 내용 수정
=> [Fix] 매칭 취소 시 상대방에 의한 취소 삭제 #22

components/match/MatchSlot.tsx, components/modal/match/MatchChallengeModal.tsx, components/modal/match/MatchEnrollModal.tsx
- 이미 차 있는 매치 등록했을때 set error 아니라 alert로 수정
- 이미 차 있는 매치 등록했을때 set error가 되는걸 alert을 띄우도록 수정하고 매치 슬롯 리로드되도록 변경
=> [Fix] 이미 차 있는 매치 등록했을때 set error 아니라 alert로 수정 #30

components/modal/afterGame/MatchTeams.tsx, styles/modal/AfterGameModal.module.scss
- 점수입력창 사용자명 길 때 밀려지는 현상 수정
- width를 정해줌
=> [Style] 점수입력창 사용자명 길 때 밀려지는 현상 수정 #19

components/match/MatchSlot.tsx
- 매치슬롯 -> 매칭 잡은 슬롯으로 자동 스크롤 
- scrollIntoView 추가
=> [Feat] 매치리스트 잡은 매치슬롯으로 자동 스크롤 #37

components/match/MatchBoard.tsx, components/match/MatchSlot.tsx, components/match/MatchSlotList.tsx
- 예약된 매치가 없을 경우 첫  open 슬롯으로 스크롤
- 안쓰는 코드 삭제
- 상단 open슬롯 스크롤 추가
=> [Feat] 최상단 open슬롯으로 스크롤 추가#37

pages/match.tsx, types/matchTypes.ts, utils/recoil/match.ts
- currentMatch 확인해 매칭의 타입을 확인해 매치 페이지에서 모드를 변경
- 힌 매칭이 있으면 매칭이 있는 곳으로 스크롤 되지만 모드가 다르면 매칭이 회색으로 보이는 문제를 currentMatch의 모드를 확인해 체크박스 모드 변경해 해결
=> [Feat] 예정된 매칭이 있을 때 체크박스 모드 확인해 변경 #40

components/Layout/Footer.tsx, components/Layout/Header.tsx, components/Layout/MenuBar.tsx
- 메뉴바, 헤더, 푸터에 공지사항 및 페이지 가이드 링크 정리
- 헤더에서 노션 링크 삭제
- 메뉴바에서 노션 링크 삭제
- 푸터에 깃헙 링크 변경
페이지 가이드는 일단 구버전 페이지 가이드로 올려놓았습니다:) 추후 변경된다면 수정해주세요~🧚‍♂️
=> [Fix] 메뉴바, 헤더, 푸터에 공지사항 및 페이지 가이드 링크 정리

components/Layout/MenuBar.tsx, components/main/SearchBar.tsx, components/mode/modeItems/UserGameSearchBar.tsx
- 영어 숫자 검색 안되도록 제한 및 관리자 로그인 버튼 추가
- 관리자 페이지로 이동할때 토큰 쿼리로 주도록 변경
- 모든 유저 검색에서 영어 검색 제한
=> [Feat] 관리자 로그인 버튼 및 영어 숫자 검색 안되도록 제한 #50

components/main/SearchBar.tsx, components/mode/modeItems/UserGameSearchBar.tsx
- 검색에 공백 포함되도록 수정
- 검색에 공백 포함되도록 정규표현식 수정
=> [Fix] 검색에 공백 포함되도록 수정 #54

styles/Layout/Layout.module.scss
=> [Style] 모바일 높이에 맞게 수정 Close #56

components/Layout/Layout.tsx, styles/Layout/Layout.module.scss, styles/Login.module.scss, styles/common.scss, styles/globals.css, styles/match/MatchBoard.module.scss
- 화면 css 수정
- 메인 페이지에 어드민 MatchTrigger 버튼 css 수정했습니다.
- 페이지 콘텐트와 푸터를 감싸는 div 추가 했습니다.
=> [Style] 화면 css 수정 #56

components/modal/afterGame/RankGame.tsx, components/modal/afterGame/Score.tsx
- 점수 입력 자판이 숫자 자판으로 뜨고 엔터로 제출 되도록 변경
- 점수 입력 타입 숫자로 바꾸고 0 ~ 5 밖 범위 입력 못하도록 변경
- 엔터키로 점수 입력되도록 추가
=> [Feat] 점수 입력 자판이 숫자 자판으로 뜨고 엔터로 제출 되도록 변경 #60

components/modal/event/WelcomeModal.tsx, styles/common.scss, styles/game/GameResultEmpty.module.scss, styles/game/GameResultItem.module.scss, styles/match/match.module.scss, styles/modal/MatchChallengeModal.module.scss, styles/modal/MatchManualModal.module.scss, styles/modal/MatchTriggerModal.module.scss, styles/modal/ReportModal.module.scss, styles/modal/WelcomeModal.module.scss, styles/rank/RankList.module.scss, styles/rank/RankListMain.module.scss
- 웰컴 모달에 유저 이름 추가
- 그림자 스타일 이름을 바꿨습니다.
=> [Feat] 웰컴 모달 유저 이름 #63

styles/rank/RankList.module.scss
- 랭크페이지 일반전 Id 및 상태메시지 길이 수정 
- css파일 overflow 및 text-overflow 추가
=> [Fix] 랭크페이지 id길이 수정 #64

styles/match/MatchBoard.module.scss, styles/match/MatchSlotList.module.scss
- 소소한 CSS 수정
- 슬롯 리스트 상하 마진 수정
=> [Style] 소소한 CSS 수정 #70

components/rank/MyRank.tsx, components/rank/RankList.tsx, components/rank/RankListFrame.tsx, components/rank/RankListItem.tsx, pages/rank.tsx, styles/rank/RankList.module.scss, types/rankTypes.ts, utils/recoil/myRank.ts
- 랭크 페이지 스크롤 고장남 해결
- scroll 리코일 상태 추가했습니다.
- myRank가 눌렸음을 확인할 수 있는 clicked 변수를 myRank 타입에 추가했습니다.
=> [Fix] 스크롤 고장남 해결 #67

components/Layout/Layout.tsx
=> [Fix] 페이지 이동 시 스크롤 상단 이동 #75

styles/Error.module.scss
- 정말_소소한_css_수정
- 404 강아지 오른쪽 여백 제거
=> [Style] 정말 소소한 css 수정 #74

components/Layout/Header.tsx, components/Layout/Layout.tsx, components/rank/RankList.tsx, pages/rank.tsx, styles/Layout/Layout.module.scss, types/rankTypes.ts, utils/recoil/myRank.ts
=> [Fix] 스크롤 에러 진짜 진짜 다고치기 #79
